### PR TITLE
Add RBAC support for backfill plugin

### PR DESCRIPTION
**Pull request by icyfox-bupt**
Hi, 

Airflow is imported RBAC and flask app builder will be the default view in 2.0.0. As I use airflow under RBAC, I add some code to support it.

Could you review the codes and merge it?

You can see [airflow_plugin_rbac_test](https://github.com/felipegasparini/airflow_plugin_rbac_test) and [airflow-rest-api-plugin](https://github.com/teamclairvoyant/airflow-rest-api-plugin) to get some info.

Thanks

### CODE REVIEW

**Comment by ankurnuk365** [comment]
Hi,

We'll review the code and test it. Post which if everything is fine, we'll merge it.

Thanks a lot for your contribution :)

**Comment by icyfox-bupt** [comment]
I have deployed this in my team and RBAC looks good, (But the UI is still too simple =.=, I'm not good at html&js )

**Comment by ankurnuk365** [comment]
> I have deployed this in my team and RBAC looks good, (But the UI is still too simple =.=, I'm not good at html&js )

This looks okay to me. I am approving it. 
We'll make changes to UI with time.

Thanks for your contribution :)

**Comment by ankurnuk365** [comment]
> I have deployed this in my team and RBAC looks good, (But the UI is still too simple =.=, I'm not good at html&js )

This looks okay to me. I am approving it.
We'll make changes to UI with time.

Thanks for your contribution :)

**Pull request merged**
